---
kind: Template
apiVersion: v1
metadata:
  name: hello-world
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: nodejs
    labels:
      shared: 'true'
  spec:
    lookupPolicy:
      local: true
    tags:
    - name: '12-ubi8'
      annotations:
      from:
        kind: DockerImage
        name: nodejs:12-ubi8
      importPolicy: {}
      referencePolicy:
        type: Source
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    creationTimestamp:
    labels:
      shared: 'true'
    annotations:
      description: Keeps track of changes in the application image
  spec:
    lookupPolicy:
      local: false
    tags: []
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
      buildconfig: "${NAME}"
  spec:
    source:
      git: https://github.com/poornima-sivanand/hello-world-nodejs.git
      ref: master
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: nodejs:12-ubi8
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:${VERSION}"
    completionDeadlineSeconds: 600
    triggers:
    - type: ConfigChange
    - type: ImageChange
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the objects defined in this template.
  required: true
  value: hello-world
- name: VERSION
  required: true
  value: '1.0'